### 3.1.5 출력과 문자열 치환

In [1]:
print('Python for Finance')

Python for Finance


In [2]:
print(t)

NameError: name 't' is not defined

In [3]:
i=0
while i<4:
    print(i)
    i+=1

0
1
2
3


In [5]:
i=0

while i<4:
    print(i, end='|')
    i+=1

0|1|2|3|

In [6]:
'this is an integer {:d}'.format(15)

'this is an integer 15'

In [7]:
'this is an integer {:4d}'.format(15)

'this is an integer   15'

In [8]:
'this is an integer {:04d}'.format(15)

'this is an integer 0015'

In [9]:
'this is a float {:f}'.format(15.3456)

'this is a float 15.345600'

In [10]:
'this is a float {:.2f}'.format(15.3456)

'this is a float 15.35'

In [11]:
'this is a float {:8f}'.format(15.3456)

'this is a float 15.345600'

In [12]:
'this is a float {:8.2f}'.format(15.3456)

'this is a float    15.35'

In [13]:
'this is a float {:08.2f}'.format(15.3456)

'this is a float 00015.35'

In [14]:
'this is a string {:s}'.format('Python')

'this is a string Python'

### 3.1.6 정규표현식

In [15]:
import re

dt=re.compile("'[0-9/:\s]+'")
dt

re.compile(r"'[0-9/:\s]+'", re.UNICODE)

In [16]:
series="""
'01/18/2014 13:00:00', 100, '1st';
'01/18/2014 13:00:00', 110, '2nd';
'01/18/2014 14:00:00', 120, '3rd'
"""

In [17]:
result=dt.findall(series)

In [18]:
result

["'01/18/2014 13:00:00'", "'01/18/2014 13:00:00'", "'01/18/2014 14:00:00'"]

In [20]:
from datetime import datetime
pydt=datetime.strptime(result[0].replace("'",""),
                      '%m/%d/%Y %H:%M:%S')
pydt

datetime.datetime(2014, 1, 18, 13, 0)

In [21]:
print(pydt)

2014-01-18 13:00:00


In [22]:
print(type(pydt))

<class 'datetime.datetime'>


## 3.2 기본 자료구조

### 3.2.1 튜플

In [23]:
t=(1,2.5, 'data')
type(t)

tuple

In [24]:
t=1,2.5,'data'
type(t)

tuple

In [25]:
t[2]

'data'

In [26]:
t.count('data')

1

In [27]:
t.index(1)

0

### 3.2.2 리스트

In [28]:
l=[1, 2.5, 'data']
l[2]

'data'

In [29]:
l=list(t)
l

[1, 2.5, 'data']

In [30]:
type(l)

list

### 3.2.3 제어구조

In [31]:
r=range(0,8,1)
r

range(0, 8)

In [32]:
type(r)

range

In [33]:
for i in range(1,10):
    if i%2==0:
        print('even')
    elif i%3==0:
        print('3으로 나뉘어짐')
    else:
        print('odd')

odd
even
3으로 나뉘어짐
even
odd
even
odd
even
3으로 나뉘어짐


In [34]:
m=[i**2 for i in range(5)]
m

[0, 1, 4, 9, 16]

### 3.2.4 함수형 프로그래밍

In [35]:
def f(x):
    return x**2
f(2)

4

In [36]:
def even(x):
    return x%2==0
even(3)

False

In [37]:
list(map(lambda x:x**2,range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [38]:
list(filter(even, range(15)))

[0, 2, 4, 6, 8, 10, 12, 14]

### 3.2.5 사전

In [39]:
d={
    'Name':'Angela Merkel',
    'Country':'Germany',
    'Profession':'Chancelor',
    'Age':64
}

type(d)

dict

In [40]:
print(d['Name'], d['Age'])

Angela Merkel 64


In [41]:
d.keys()

dict_keys(['Name', 'Country', 'Profession', 'Age'])

In [42]:
d.values()

dict_values(['Angela Merkel', 'Germany', 'Chancelor', 64])

In [44]:
d.items()

dict_items([('Name', 'Angela Merkel'), ('Country', 'Germany'), ('Profession', 'Chancelor'), ('Age', 64)])

### 3.2.6 집합

In [45]:
s=set(['u','d','ud','du','d','du'])
s

{'d', 'du', 'u', 'ud'}

In [46]:
t=set(['d','dd','uu','u'])

In [47]:
s.union(t)

{'d', 'dd', 'du', 'u', 'ud', 'uu'}

In [48]:
s.intersection(t)

{'d', 'u'}

In [49]:
s.difference(t)

{'du', 'ud'}

In [51]:
t.difference(s)

{'dd', 'uu'}

In [52]:
s.symmetric_difference(t)

{'dd', 'du', 'ud', 'uu'}

# Numpy를 사용한 수치 계산

# 4.1 데이터 배열
### 4.1.1 파이썬 리스트를 사용한 배열

In [53]:
v=[0.5, 0.75, 1.0, 1.5, 2.0]

In [54]:
m=[v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [55]:
v1=[0.5, 1.5]
v2=[1,2]
m=[v1,v2]
c=[m,m]
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

### 4.1.2 파이썬 array 클래스

In [56]:
v=[0.5, 0.75, 1.0, 1.5, 2.0]

import array

a=array.array('f', v)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [57]:
a.append(0.5)

In [58]:
a.extend([5.0, 6.75])

In [59]:
2*a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

## 4.2 정규 Numpy 배열

### 4.2.1 기초

In [60]:
import numpy as np

a=np.array([0, 0.5, 1.0, 1.5, 2.0])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [61]:
type(a)

numpy.ndarray

In [62]:
a=np.array(['a','b','c'])
a

array(['a', 'b', 'c'], dtype='<U1')

In [63]:
a=np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [64]:
a=np.arange(8, dtype=np.float)
a

C:\Users\azin1\AppData\Local\Temp\ipykernel_24400\2676705182.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.arange(8, dtype=np.float)


array([0., 1., 2., 3., 4., 5., 6., 7.])

In [65]:
a[5:]

array([5., 6., 7.])

In [66]:
a[:2]

array([0., 1.])

In [67]:
a.sum()

28.0

In [68]:
a.std()

2.29128784747792

In [69]:
a.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [70]:
l=[0., 0.5, 1.5, 3., 5.]
2*l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [71]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [72]:
2*a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [73]:
a**2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [74]:
2**a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [75]:
a**a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])