## 4.2.1 기초

In [2]:
import numpy as np

In [3]:
np.sqrt(2.5)

1.5811388300841898

In [4]:
import math

In [5]:
math.sqrt(2.5)

1.5811388300841898

## 4.2.2 다차원

In [7]:
a=np.arange(8, dtype=np.float)
b=np.array([a, a*2])
b

<ipython-input-7-aa3abdfb51f9>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.arange(8, dtype=np.float)


array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [8]:
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [9]:
b[0,2]

2.0

In [10]:
b[:,1]

array([1., 2.])

In [11]:
b.sum()

84.0

In [12]:
b.sum(axis=0)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [13]:
b.sum(axis=1)

array([28., 56.])

In [14]:
c=np.zeros((2,3), dtype='i', order='C')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [16]:
c=np.ones((2,3,4), dtype='i', order='C')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [17]:
d=np.zeros_like(c, dtype='f16', order='C')
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float128)

In [18]:
d=np.ones_like(c, dtype='f16', order='C')
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float128)

In [20]:
e=np.empty((2,3,2))
e

array([[[2.27920467e-316, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [21]:
f=np.empty_like(c)
f

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
g=np.linspace(5,15,12)
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

## 4.2.3 메타정보

In [24]:
g.size

12

In [25]:
g.itemsize

8

In [26]:
g.ndim

1

In [27]:
g.shape

(12,)

In [28]:
g.dtype

dtype('float64')

In [29]:
g.nbytes

96

## 4.2.4 형태 변환과 크기 변환

In [30]:
g=np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
g.shape

(15,)

In [32]:
np.shape(g)

(15,)

In [33]:
g.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
h=g.reshape((5,3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [35]:
h.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [36]:
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [38]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
np.resize(g, (3,1))

array([[0],
       [1],
       [2]])

In [40]:
np.resize(g, (1,5))

array([[0, 1, 2, 3, 4]])

In [41]:
np.resize(g, (2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 스택 연산

In [43]:
n=np.resize(g, (5,4))
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

In [44]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [46]:
np.hstack((h, 2*h))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [47]:
np.vstack((h, 0.5*h))

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

### 벡터화

In [48]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [49]:
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
h.flatten(order='C') # 열 순서로 펼치기

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
h.flatten(order='F') # 행 순서로 펼치기

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [54]:
for i in h.flat:
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [55]:
for i in h.ravel(order='C'):
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [56]:
for i in h.ravel(order='F'):
    print(i, end=',')

0,3,6,9,12,1,4,7,10,13,2,5,8,11,14,

## 4.2.5 불리언 배열

In [57]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [58]:
h>8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [59]:
h<=7

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [60]:
h==5

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [61]:
(h==5).astype(int)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [62]:
(h>4)&(h<=12)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [63]:
h[h>8]

array([ 9, 10, 11, 12, 13, 14])

#### np.where()

In [64]:
np.where(h>7, 1, 0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [65]:
np.where(h%2==0, 'even', 'odd')

array([['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even']], dtype='<U4')

In [67]:
np.where(h<=7, h*2,h/2)

array([[ 0. ,  2. ,  4. ],
       [ 6. ,  8. , 10. ],
       [12. , 14. ,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

## 4.2.6 속도 비교

#### 파이썬

In [68]:
# 파이썬, numpy 비교

import random
I=5000

%time mat=[[random.gauss(0,1) for j in range(I)] for i in range(I)]

CPU times: user 19 s, sys: 666 ms, total: 19.7 s
Wall time: 19.8 s


In [69]:
%time sum([sum(l) for l in mat])

CPU times: user 180 ms, sys: 872 µs, total: 181 ms
Wall time: 194 ms


1199.674331791875

In [70]:
import sys
sum([sys.getsizeof(l) for l in mat]) # 리스트 원소가 사용한 메모리의 합

215160000

#### numpy

In [71]:
%time mat=np.random.standard_normal((I,I)) # 표준정규분포 난수

CPU times: user 737 ms, sys: 57 ms, total: 794 ms
Wall time: 794 ms


In [72]:
%time mat.sum()

CPU times: user 21.2 ms, sys: 0 ns, total: 21.2 ms
Wall time: 21.8 ms


6990.061156391917

In [73]:
mat.nbytes

200000000

In [74]:
sys.getsizeof(mat)

200000128

# 4.3 구조화 numpy 배열

In [75]:
dt=np.dtype([('Name','S10'), ('Age','i4'), ('Height','f'), ('Children/Pets','i4',2)])

In [76]:
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [78]:
dt=np.dtype({'names':['Name','Age','Height','Children/Pets'],
             'formats':'0 int float int,int'.split()})

TypeError: ignored

In [79]:
s=np.array([('Smith',45,1.83,(0,1)), ('Jones',53,1.72, (2,2))], dtype=dt)

In [80]:
s

array([(b'Smith', 45, 1.83, [0, 1]), (b'Jones', 53, 1.72, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [81]:
type(s)

numpy.ndarray

In [82]:
s['Name']

array([b'Smith', b'Jones'], dtype='|S10')

In [83]:
s['Height'].mean()

1.7750001

In [84]:
s[0]

(b'Smith', 45, 1.83, [0, 1])

In [85]:
s[1]['Age']

53

# 4.4 코드 벡터화
## 4.4.1 기본적인 벡터화

In [86]:
np.random.seed(100)

In [87]:
r=np.arange(12).reshape((4,3))
s=np.arange(12).reshape((4,3))*0.5

In [88]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [89]:
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [90]:
r+s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [92]:
# 브로드캐스팅

r+3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [93]:
r.shape

(4, 3)

In [95]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [94]:
s=np.arange(0,12,4)
s

array([0, 4, 8])

In [96]:
r+s

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [97]:
s=np.arange(0,12,3)
s

array([0, 3, 6, 9])

In [98]:
r+s

ValueError: ignored

In [99]:
r.transpose()+s

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [100]:
sr=s.reshape(-1,1)

In [101]:
sr

array([[0],
       [3],
       [6],
       [9]])

In [102]:
sr.shape

(4, 1)

In [103]:
r+sr

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [104]:
def f(x):
    return 3*x +5

f(0.5)

6.5

In [105]:
f(r)

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

## 4.4.2 메모리 레이아웃

In [106]:
# 배열의 각 원소가 메모리상에 저장되는 방식

x=np.random.standard_normal((1000000,5))

y=2*x+3

C=np.array((x,y), order='C')

F=np.array((x,y), order='F')

x=0.0; y=0.0

In [107]:
C[:2].round(2)

array([[[-1.75,  0.34,  1.15, -0.25,  0.98],
        [ 0.51,  0.22, -1.07, -0.19,  0.26],
        [-0.46,  0.44, -0.58,  0.82,  0.67],
        ...,
        [-0.05,  0.14,  0.17,  0.33,  1.39],
        [ 1.02,  0.3 , -1.23, -0.68, -0.87],
        [ 0.83, -0.73,  1.03,  0.34, -0.46]],

       [[-0.5 ,  3.69,  5.31,  2.5 ,  4.96],
        [ 4.03,  3.44,  0.86,  2.62,  3.51],
        [ 2.08,  3.87,  1.83,  4.63,  4.35],
        ...,
        [ 2.9 ,  3.28,  3.33,  3.67,  5.78],
        [ 5.04,  3.6 ,  0.54,  1.65,  1.26],
        [ 4.67,  1.54,  5.06,  3.69,  2.07]]])

In [108]:
%timeit C.sum()

9.95 ms ± 378 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [109]:
%timeit F.sum()

9.3 ms ± 45.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [110]:
%timeit C.sum(axis=0)

19.2 ms ± 805 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [111]:
%timeit C.sum(axis=1)

59.4 ms ± 12.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [112]:
%timeit F.sum(axis=0)

105 ms ± 2.77 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [113]:
%timeit F.sum(axis=1)

110 ms ± 1.25 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
